-- Update team flags using flagcdn.com
-- Format: https://flagcdn.com/w40/{iso2}.png

UPDATE public.matches SET
  home_team_flag = CASE home_team
    WHEN 'Mexico'                  THEN 'https://flagcdn.com/w40/mx.png'
    WHEN 'South Korea'             THEN 'https://flagcdn.com/w40/kr.png'
    WHEN 'South Africa'            THEN 'https://flagcdn.com/w40/za.png'
    WHEN 'Czechia'                 THEN 'https://flagcdn.com/w40/cz.png'
    WHEN 'Canada'                  THEN 'https://flagcdn.com/w40/ca.png'
    WHEN 'Switzerland'             THEN 'https://flagcdn.com/w40/ch.png'
    WHEN 'Qatar'                   THEN 'https://flagcdn.com/w40/qa.png'
    WHEN 'Bosnia and Herzegovina'  THEN 'https://flagcdn.com/w40/ba.png'
    WHEN 'Brazil'                  THEN 'https://flagcdn.com/w40/br.png'
    WHEN 'Morocco'                 THEN 'https://flagcdn.com/w40/ma.png'
    WHEN 'Scotland'                THEN 'https://flagcdn.com/w40/gb-sct.png'
    WHEN 'Haiti'                   THEN 'https://flagcdn.com/w40/ht.png'
    WHEN 'United States'           THEN 'https://flagcdn.com/w40/us.png'
    WHEN 'Australia'               THEN 'https://flagcdn.com/w40/au.png'
    WHEN 'Paraguay'                THEN 'https://flagcdn.com/w40/py.png'
    WHEN 'Turkey'                  THEN 'https://flagcdn.com/w40/tr.png'
    WHEN 'Germany'                 THEN 'https://flagcdn.com/w40/de.png'
    WHEN 'Ecuador'                 THEN 'https://flagcdn.com/w40/ec.png'
    WHEN 'Ivory Coast'             THEN 'https://flagcdn.com/w40/ci.png'
    WHEN 'Curacao'                 THEN 'https://flagcdn.com/w40/cw.png'
    WHEN 'Netherlands'             THEN 'https://flagcdn.com/w40/nl.png'
    WHEN 'Japan'                   THEN 'https://flagcdn.com/w40/jp.png'
    WHEN 'Tunisia'                 THEN 'https://flagcdn.com/w40/tn.png'
    WHEN 'Sweden'                  THEN 'https://flagcdn.com/w40/se.png'
    WHEN 'Belgium'                 THEN 'https://flagcdn.com/w40/be.png'
    WHEN 'Iran'                    THEN 'https://flagcdn.com/w40/ir.png'
    WHEN 'Egypt'                   THEN 'https://flagcdn.com/w40/eg.png'
    WHEN 'New Zealand'             THEN 'https://flagcdn.com/w40/nz.png'
    WHEN 'Spain'                   THEN 'https://flagcdn.com/w40/es.png'
    WHEN 'Uruguay'                 THEN 'https://flagcdn.com/w40/uy.png'
    WHEN 'Saudi Arabia'            THEN 'https://flagcdn.com/w40/sa.png'
    WHEN 'Cape Verde'              THEN 'https://flagcdn.com/w40/cv.png'
    WHEN 'France'                  THEN 'https://flagcdn.com/w40/fr.png'
    WHEN 'Senegal'                 THEN 'https://flagcdn.com/w40/sn.png'
    WHEN 'Norway'                  THEN 'https://flagcdn.com/w40/no.png'
    WHEN 'Iraq'                    THEN 'https://flagcdn.com/w40/iq.png'
    WHEN 'Argentina'               THEN 'https://flagcdn.com/w40/ar.png'
    WHEN 'Austria'                 THEN 'https://flagcdn.com/w40/at.png'
    WHEN 'Algeria'                 THEN 'https://flagcdn.com/w40/dz.png'
    WHEN 'Jordan'                  THEN 'https://flagcdn.com/w40/jo.png'
    WHEN 'Portugal'                THEN 'https://flagcdn.com/w40/pt.png'
    WHEN 'Colombia'                THEN 'https://flagcdn.com/w40/co.png'
    WHEN 'Uzbekistan'              THEN 'https://flagcdn.com/w40/uz.png'
    WHEN 'DR Congo'                THEN 'https://flagcdn.com/w40/cd.png'
    WHEN 'England'                 THEN 'https://flagcdn.com/w40/gb-eng.png'
    WHEN 'Croatia'                 THEN 'https://flagcdn.com/w40/hr.png'
    WHEN 'Panama'                  THEN 'https://flagcdn.com/w40/pa.png'
    WHEN 'Ghana'                   THEN 'https://flagcdn.com/w40/gh.png'
    ELSE home_team_flag
  END,
  away_team_flag = CASE away_team
    WHEN 'Mexico'                  THEN 'https://flagcdn.com/w40/mx.png'
    WHEN 'South Korea'             THEN 'https://flagcdn.com/w40/kr.png'
    WHEN 'South Africa'            THEN 'https://flagcdn.com/w40/za.png'
    WHEN 'Czechia'                 THEN 'https://flagcdn.com/w40/cz.png'
    WHEN 'Canada'                  THEN 'https://flagcdn.com/w40/ca.png'
    WHEN 'Switzerland'             THEN 'https://flagcdn.com/w40/ch.png'
    WHEN 'Qatar'                   THEN 'https://flagcdn.com/w40/qa.png'
    WHEN 'Bosnia and Herzegovina'  THEN 'https://flagcdn.com/w40/ba.png'
    WHEN 'Brazil'                  THEN 'https://flagcdn.com/w40/br.png'
    WHEN 'Morocco'                 THEN 'https://flagcdn.com/w40/ma.png'
    WHEN 'Scotland'                THEN 'https://flagcdn.com/w40/gb-sct.png'
    WHEN 'Haiti'                   THEN 'https://flagcdn.com/w40/ht.png'
    WHEN 'United States'           THEN 'https://flagcdn.com/w40/us.png'
    WHEN 'Australia'               THEN 'https://flagcdn.com/w40/au.png'
    WHEN 'Paraguay'                THEN 'https://flagcdn.com/w40/py.png'
    WHEN 'Turkey'                  THEN 'https://flagcdn.com/w40/tr.png'
    WHEN 'Germany'                 THEN 'https://flagcdn.com/w40/de.png'
    WHEN 'Ecuador'                 THEN 'https://flagcdn.com/w40/ec.png'
    WHEN 'Ivory Coast'             THEN 'https://flagcdn.com/w40/ci.png'
    WHEN 'Curacao'                 THEN 'https://flagcdn.com/w40/cw.png'
    WHEN 'Netherlands'             THEN 'https://flagcdn.com/w40/nl.png'
    WHEN 'Japan'                   THEN 'https://flagcdn.com/w40/jp.png'
    WHEN 'Tunisia'                 THEN 'https://flagcdn.com/w40/tn.png'
    WHEN 'Sweden'                  THEN 'https://flagcdn.com/w40/se.png'
    WHEN 'Belgium'                 THEN 'https://flagcdn.com/w40/be.png'
    WHEN 'Iran'                    THEN 'https://flagcdn.com/w40/ir.png'
    WHEN 'Egypt'                   THEN 'https://flagcdn.com/w40/eg.png'
    WHEN 'New Zealand'             THEN 'https://flagcdn.com/w40/nz.png'
    WHEN 'Spain'                   THEN 'https://flagcdn.com/w40/es.png'
    WHEN 'Uruguay'                 THEN 'https://flagcdn.com/w40/uy.png'
    WHEN 'Saudi Arabia'            THEN 'https://flagcdn.com/w40/sa.png'
    WHEN 'Cape Verde'              THEN 'https://flagcdn.com/w40/cv.png'
    WHEN 'France'                  THEN 'https://flagcdn.com/w40/fr.png'
    WHEN 'Senegal'                 THEN 'https://flagcdn.com/w40/sn.png'
    WHEN 'Norway'                  THEN 'https://flagcdn.com/w40/no.png'
    WHEN 'Iraq'                    THEN 'https://flagcdn.com/w40/iq.png'
    WHEN 'Argentina'               THEN 'https://flagcdn.com/w40/ar.png'
    WHEN 'Austria'                 THEN 'https://flagcdn.com/w40/at.png'
    WHEN 'Algeria'                 THEN 'https://flagcdn.com/w40/dz.png'
    WHEN 'Jordan'                  THEN 'https://flagcdn.com/w40/jo.png'
    WHEN 'Portugal'                THEN 'https://flagcdn.com/w40/pt.png'
    WHEN 'Colombia'                THEN 'https://flagcdn.com/w40/co.png'
    WHEN 'Uzbekistan'              THEN 'https://flagcdn.com/w40/uz.png'
    WHEN 'DR Congo'                THEN 'https://flagcdn.com/w40/cd.png'
    WHEN 'England'                 THEN 'https://flagcdn.com/w40/gb-eng.png'
    WHEN 'Croatia'                 THEN 'https://flagcdn.com/w40/hr.png'
    WHEN 'Panama'                  THEN 'https://flagcdn.com/w40/pa.png'
    WHEN 'Ghana'                   THEN 'https://flagcdn.com/w40/gh.png'
    ELSE away_team_flag
  END
WHERE api_match_id LIKE 'wc26-%';
