export const PRODUCTS = [
  {
    id: 'p01',
    name: 'טי-שירט טקטי',
    category: 'חולצות',
    description: 'חולצת DryFit קצרה, בד נושם, צווארון עגול',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    color1: '#0d1b2a',
    color2: '#1b2838',
    letter: 'T',
  },
  {
    id: 'p02',
    name: 'חולצת פולו',
    category: 'חולצות',
    description: 'פולו עם צווארון, בד פיקה איכותי',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    color1: '#1a0a0a',
    color2: '#2e1515',
    letter: 'P',
  },
  {
    id: 'p03',
    name: 'חולצה ארוכה טקטית',
    category: 'חולצות',
    description: 'חולצת שרוול ארוך עם רוכסן חצי, בד מתיחה',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    color1: '#0a1a0a',
    color2: '#162a16',
    letter: 'L',
    imageUrl: '/images/shirt.jpg?v=2',
  },
  {
    id: 'p04',
    name: 'גופיית אימון',
    category: 'גופיות',
    description: 'גופיה לאימון, פתחי אוורור, DryFit',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    color1: '#1a1a0a',
    color2: '#2e2e15',
    letter: 'G',
  },
  {
    id: 'p05',
    name: 'מכנסי קרגו',
    category: 'מכנסיים',
    description: 'קרגו עם 6 כיסים, בד Ripstop עמיד',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    color1: '#1e2d12',
    color2: '#2a3d1a',
    letter: 'K',
    imageUrl: '/images/cargo.jpg?v=2',
  },
  {
    id: 'p06',
    name: 'מכנסי טרנינג',
    category: 'מכנסיים',
    description: 'מכנסי ג\'וגר טכניים, כיסי רוכסן',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    color1: '#1a1020',
    color2: '#26183a',
    letter: 'J',
  },
  {
    id: 'p07',
    name: 'ג\'קט שדה',
    category: 'ג\'קטים',
    description: 'ג\'קט קל, כיסים מרובים, עמיד לרוח',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    color1: '#261a0a',
    color2: '#3a2810',
    letter: 'J',
  },
  {
    id: 'p08',
    name: 'ג\'קט מרופד',
    category: 'ג\'קטים',
    description: 'ג\'קט חורפי עם ריפוד, עמיד לקור',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    color1: '#0a1020',
    color2: '#121830',
    letter: 'W',
  },
  {
    id: 'p09',
    name: 'כובע בייסבול',
    category: 'אקססוריז',
    description: 'כובע מצחייה, רצועת וולקרו מתכווננת',
    sizes: ['One Size'],
    color1: '#1a1010',
    color2: '#2e1a1a',
    letter: 'C',
  },
  {
    id: 'p10',
    name: 'בלקלבה',
    category: 'אקססוריז',
    description: 'כיסוי ראש גמיש, פוליאסטר עבה',
    sizes: ['One Size'],
    color1: '#0a0a0a',
    color2: '#1a1a1a',
    letter: 'B',
  },
];
